# Generated by Django 4.1.1 on 2022-09-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('features', models.CharField(max_length=1000, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('pincode', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Wish_products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.user')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.user')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='OnSale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discount_per', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
            ],
        ),
    ]
