# Generated by Django 4.1.1 on 2022-09-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_pictures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='product_images')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
            ],
        ),
    ]
