# Generated by Django 4.1.1 on 2022-09-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='product_images'),
            preserve_default=False,
        ),
    ]
