# Generated by Django 4.1.1 on 2022-09-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_per',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OnSale',
        ),
    ]
