# Generated by Django 4.1.1 on 2022-09-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_rename_discount_per_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_products',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
